### ISSUE TITLE
ReferenceError: cfg is not defined

### ISSUE THREAD

**Issue by boblinux** [meandavejustice/gh-pages-deploy#27] opened 2018-05-04 09:18 UTC
Hi, here is my issue, i try to deploy some ionic app on github pages, (working on W10)
```
$ gh-pages-deploy
C:\Users\sesa488780\AppData\Roaming\npm\node_modules\gh-pages-deploy\index.js:13
var gitcommit = "git commit -a -m '" + (process.argv[3] || cfg.commit || defaultmessage) + "'";
                                                           ^

ReferenceError: cfg is not defined
    at Object.<anonymous> (C:\Users\sesa488780\AppData\Roaming\npm\node_modules\gh-pages-deploy\index.js:13:60)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\sesa488780\AppData\Roaming\npm\node_modules\gh-pages-deploy\bin\gh-pages-deploy:4:14)
    at Module._compile (module.js:652:30)
```
```
node --version
v8.11.1

npm --version
5.8.0
```
```

$ uname -a
MINGW64_NT-10.0 WTFRLVSE078714L 2.9.0(0.318/5/3) 2018-01-12 23:37 x86_64 Msys
```

Edit : i tried on docker alpine linux, same issue (even with installing cfg & cfg-js with npm... it still be not defined =/ )
```
uname -a
Linux 5efa6ad6bad2 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 Linux
```

**Comment by meandavejustice** [comment] 2018-05-04 16:10
closing as dupe of #26

**Closed by meandavejustice** 2018-05-04 16:10 UTC
